# Generated by Django 3.1.2 on 2020-12-21 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pybo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0006_auto_20200507_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='download_flag',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='upload_target',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FileField(blank=True, null=True, upload_to=pybo.models.Upload.get_file_path, verbose_name='파일경로')),
                ('filefolder', models.CharField(blank=True, max_length=1000, null=True, verbose_name='파일폴더')),
                ('filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='파일명')),
                ('subject', models.CharField(max_length=200, null=True, verbose_name='제목')),
                ('tag', models.CharField(max_length=200, null=True, verbose_name='태그')),
                ('create_date', models.DateTimeField(null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_upload', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
