# Generated by Django 3.1.2 on 2020-12-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20201222_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='download_flag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
