# Generated by Django 3.1.2 on 2021-01-07 12:31

from django.db import migrations, models
import pybo.models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_auto_20201225_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='filepath',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=pybo.models.Upload.get_file_path, verbose_name='파일경로'),
        ),
    ]
