# Generated by Django 3.1.2 on 2021-01-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_auto_20210107_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
