# Generated by Django 3.1.2 on 2021-01-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0012_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='upload_flag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
