# Generated by Django 3.1.2 on 2021-01-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0014_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='thumbnail_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='youtube',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
