# Generated by Django 3.1.2 on 2021-01-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0016_youtube_thumbnail_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
